---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: enable nginx
  service:
    name: nginx
    enabled: yes

- name: Enable large file uploads needed for import
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: client_max_body_size
    insertafter: '^http {$'
    line: "\tclient_max_body_size 2G;"
  notify:
    - 'Restart nginx'

- name: disable default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: 'Restart nginx'

- name: Allow port 80 and 443 in
  ufw:
    name: 'Nginx Full'
    direction: in
    rule: allow
    state: enabled
