---

- name: check if cert is present
  stat:
    path: '/etc/letsencrypt/live/{{ ipt_domain }}/fullchain.pem'
  register: stat_result

- name: Set the http baseURL in IPT config
  template:
    src: ipt.properties.j2
    dest: '{{ ipt_data_dir }}/config/ipt.properties'
    owner: tomcat
    group: tomcat
  vars:
    ipt_base_url: 'http\://{{ ansible_default_ipv4.address }}/ipt'
  when: not stat_result.stat.exists

- name: Set the https baseURL in IPT config
  template:
    src: ipt.properties.j2
    dest: '{{ ipt_data_dir }}/config/ipt.properties'
    owner: tomcat
    group: tomcat
  vars:
    ipt_base_url: 'https\://{{ ipt_domain }}/ipt'
  when: stat_result.stat.exists
