---

# This role was written for Ubuntu Server LTS 20.04. The prerequisits are a
# freshly installed server with a user provisioning with the password set as
# defined in the vault variable vault_provisioning_user_password.
- name: Accounts
  block:
    - name: Create admin users with empty passwords and add to sudo group
      user:
        state: present
        name: '{{ item.key }}'
        uid: '{{ item.value.uid }}'
        comment: '{{ item.value.full_name }}'
        shell: /usr/bin/bash
        create_home: yes
        groups: 'sudo'
        append: yes
      loop: '{{ phase_1_admin_users | dict2items }}'

    - name: Allow sudo group member to use sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo	ALL='
        line: '%sudo	ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

- name: SSH
  block:
    - name: set up pubkey based auth by installing pubkeys
      ansible.posix.authorized_key:
        user: "{{ item.key }}"
        state: present
        key: "{{ item.value.pubkey }}"
      loop: '{{ phase_1_admin_users | dict2items }}'

    - name: switch off password based logins
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication"
        line: PasswordAuthentication no

    - name: reload sshd to apply password auth change
      service:
        name: sshd
        state: reloaded

    - name: Reconnect since sshd was reloaded
      meta: reset_connection
