---

- name: Install dependencies
  apt:
    name:
      - php
      - python3
    state: latests

- name: Create deployment directory
  file:
    path: '{{ data_cache_deploy_directory }}'
    state: directory
    owner: www-data
    group: www-data

- name: Download data_cache sources
  git:
    repo: 'https://{{ gitlab_deploy_user }}:{{ gitlab_deploy_password }}@gitlab.mnhn.lu/section-BD/automated-tasks/data-cache.git'
    dest: '{{ data_cache_deploy_directory }}'
    version: master
    force: yes
  vars:
    gitlab_deploy_user: '{{ vault_gitlab_deploy_user }}'
    gitlab_deploy_password: '{{ vault_gitlab_deploy_password }}'

- name: Configure data_cache
  template:
    src: _config.php.j2
    dest: '{{ data_cache_deploy_directory }}/_config.php'

- name: Crontab recorder neobiota
  cron:
    name: Recorder neobiota ETL
    cron_file: data_cache_neobiota
    state: present
    user: mnhn
    job: 'python3 {{ data_cache_deploy_directory }}/recorder_neobiota/recorder_neobiota.py >> {{ data_cache_deploy_directory }}/recorder_neobiota/recorder_neobiota.log'
    minute: 0
    hour: 6

- name: Crontab fetch weather
  cron:
    name: Weather ETL
    cron_file: data_cache_weather
    state: present
    user: mnhn
    job: 'php {{ data_cache_deploy_directory }}/fetch_weather_data_meteolux.php >> {{ data_cache_deploy_directory }}/log/fetch_weather_data_meteolux.log'
    minute: 1
    hour: 19
    weekday: '1-6'

- name: Crontab inaturalist 1
  cron:
    name: iNaturalist ETL 1
    cron_file: data_cache_inaturalist
    state: present
    user: mnhn
    job: 'php {{ data_cache_deploy_directory }}/inaturalist_update_cache.php >> {{ data_cache_deploy_directory }}/log/inaturalist_update_cache.log'
    minute: 0
    hour: 10

- name: Crontab inaturalist 2
  cron:
    name: iNaturalist ETL 2
    cron_file: data_cache_inaturalist
    state: present
    user: mnhn
    job: 'php {{ data_cache_deploy_directory }}/inaturalist_update_cache.php >> {{ data_cache_deploy_directory }}/log/inaturalist_update_cache.log'
    minute: 0
    hour: 12


- name: Crontab inaturalist 3
  cron:
    name: iNaturalist ETL 3
    cron_file: data_cache_inaturalist
    state: present
    user: mnhn
    job: 'php {{ data_cache_deploy_directory }}/inaturalist_update_cache.php >> {{ data_cache_deploy_directory }}/log/inaturalist_update_cache.log'
    minute: 0
    hour: 14


- name: Crontab inaturalist 4
  cron:
    name: iNaturalist ETL 4
    cron_file: data_cache_inaturalist
    state: present
    user: mnhn
    job: 'php {{ data_cache_deploy_directory }}/inaturalist_update_cache.php >> {{ data_cache_deploy_directory }}/log/inaturalist_update_cache.log'
    minute: 0
    hour: 16

- name: Crontab geoportal
  cron:
    name: Geoportal ETL
    cron_file: data_cache_geoportal
    state: present
    user: mnhn
    job: '/bin/bash {{ data_cache_deploy_directory }}/geoportal/build_export.sh >> {{ data_cache_deploy_directory }}/geoportal/log/build_cache.log'
    minute: 0
    hour: 20

- name: Crontab iNaturalist neobiota alert
  cron:
    name: iNaturalist Neobiora alert
    cron_file: data_cache_neobiota_alert
    state: present
    user: mnhn
    job: 'python3 {{ data_cache_deploy_directory }}/inaturalist_neobiota_alert/INat-neobiota-allert.py >> {{ data_cache_deploy_directory }}/inaturalist_neobiota_alert/log/INat-neobiota-allert.log'
    minute: 0
    hour: 13

- name: Crontab build cache
  cron:
    name: Main cache ETL
    cron_file: data_cache_main
    state: present
    user: mnhn
    job: '/bin/bash {{ data_cache_deploy_directory }}/build_cache.sh >> {{ data_cache_deploy_directory }}/log/build_cache.log'
    minute: 0
    hour: 19
