---
# tasks file for roles/mariadb

- name: Install mariadb
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present

- name: Install and enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install ansible deps
  apt:
    name: python3-pymysql
    state: present

- name: Configure mariadb securely
  mysql_secure_installation:
    login_password: ''
    new_password: '{{ mariadb_root_password }}'
    user: root
    login_host: localhost
    hosts: ['localhost', '127.0.0.1', '::1']
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
  when: mariadb_root_password != ''
