---

argument_specs:
  main:
    options:
      domains:
        type: list
        required: yes
        description: The domains to get the certificate for

      email:
        type: str
        required: yes
        description: The email of the administrative contact
