---

- name: Ensure extraction dir exists
  file:
    path: "/tmp/nginx_site/{{ nginx_site_name }}"
    state: directory

- name: Install site htdocs to tmp
  unarchive:
    remote_src: yes
    src: "{{ nginx_site_archive_src }}"
    dest: "/tmp/nginx_site/{{ nginx_site_name }}"
  when: nginx_site_archive_src

- name: Ensure site root exists
  file:
    path: "{{ nginx_site_install_root }}"
    state: directory
    group: www-data
    owner: www-data

- name: Copy site htdocs to destination
  copy:
    remote_src: yes
    src: "/tmp/nginx_site/{{ nginx_site_name }}/{{ nginx_site_archive_subdir }}"
    dest: "{{ nginx_site_install_root }}"
  become_user: www-data

- name: Install site file from template (static)
  template:
    src: site_static.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}"
  vars:
    default_server: "{{ nginx_site_default_server }}"
    root: "{{ nginx_site_root }}"
    server_name: "{{ nginx_site_server_name }}"
    index: "{{ nginx_site_index }}"
    main_location: "{{ nginx_site_main_location }}"
  when: nginx_site_state == "enabled" and nginx_site_type == 'static'

- name: Install site file from template (cgi)
  template:
    src: site_cgi.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}"
  vars:
    default_server: "{{ nginx_site_default_server }}"
    root: "{{ nginx_site_root }}"
    server_name: "{{ nginx_site_server_names|join(' ') }}"
    fastcgi_pass: "{{ nginx_site_fastcgi_pass }}"
    fastcgi_SCRIPT_FILENAME: "{{ nginx_site_fastcgi_SCRIPT_FILENAME }}"
    index: "{{ nginx_site_index }}"
    main_location: "{{ nginx_site_main_location }}"
    cgi_location: "{{ nginx_site_cgi_location }}"
  when: nginx_site_state == "enabled" and nginx_site_type == 'cgi'

- name: Uninstall site file from template
  file:
    dest: "/etc/nginx/sites-available/{{ nginx_site_name }}"
    state: absent
  when: nginx_site_state == "disabled"

- name: Enable site
  file:
    src: "/etc/nginx/sites-available/{{ nginx_site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site_name }}"
    state: link
  when: nginx_site_state == "enabled"
  notify: 'Nginx reload'

- name: Disable site
  file:
    dest: "/etc/nginx/sites-enabled/{{ nginx_site_name }}"
    state: absent
  when: nginx_site_state == "disabled"
  notify: 'Nginx reload'

- name: Add hosts to nginx_site_https_hosts if necessary
  set_fact:
    nginx_site_https_hosts: '{{ nginx_site_https_hosts|default([]) + nginx_site_server_names }}'
  when: nginx_site_https
