---

- name: Install dependencies for postgresql modules
  apt:
    name:
      - python3-psycopg2
      - postgresql-contrib # for pg_trgm
    state: present

- name: As postgres
  become_user: postgres
  block:
    - name: Create database user
      postgresql_user:
        name: drupal
        password: '{{ drupal9_default_database_password }}'
        state: present

    - name: Create drupal9 database
      postgresql_db:
        name: drupal
        encoding: UTF-8
        owner: drupal
        state: present

- name: Create deployment directory
  file:
    path: '{{ drupal9_deploy_directory }}'
    state: directory
    owner: www-data
    group: www-data

- name: Install php dependencies
  apt:
    name:
      - php-xml # ext-dom
      - php-gd # ext-gd
      - php-pgsql
    state: latest

- name: Check if drupal9 is already installed
  stat:
    path: '{{ drupal9_directory }}'
  register: drupal_dir

- name: Create drupal install directory
  file:
    path: '{{ drupal9_directory }}'
    state: directory
    owner: www-data
    group: www-data
  when: not drupal_dir.stat.exists

- name: As www-data
  become_user: www-data
  block:
    # FIXME: handle existing installation, maybe update
    - name: Install drupal9 project using composer
      composer:
        command: create-project
        arguments: drupal/recommended-project drupal9
        working_dir: '{{ drupal9_deploy_directory }}'
      when: not drupal_dir.stat.exists
    
    - name: Install drush (drupal shell)
      composer:
        command: require
        arguments: drush/drush
        working_dir: '{{ drupal9_directory }}'
    
    - name: Install drupal9 site
      command:
        cmd: '{{ drupal9_drush}} site:install -y --db-url=pgsql://drupal:{{ drupal9_default_database_password }}@localhost/drupal'
        chdir: '{{ drupal9_directory }}'
    
    - name: Set site name
      command:
        cmd: '{{ drupal9_drush }} config:set -y system.site name "{{ drupal9_site_name }}"'
        chdir: '{{ drupal9_directory }}'
    
    - name: Reset admin password
      command:
        cmd: '{{ drupal9_drush }} user:password -y admin "{{ drupal9_default_admin_password }}"'
        chdir: '{{ drupal9_directory }}'

- name: Configure nginx to serve drupal9
  template:
    src: drupal9.j2
    dest: /etc/nginx/sites-available/drupal9
  vars:
    root: '{{ drupal9_deploy_directory }}/drupal9/web'
    host: '{{ drupal9_domain }}'
    socket_path: '/var/run/php/php-fpm.sock'
  notify:
    'Reload nginx'

- name: Activate site
  file:
    src: /etc/nginx/sites-available/drupal9
    dest: /etc/nginx/sites-enabled/drupal9
    state: link
  notify:
    'Reload nginx'
