---

- name: Install dependencies
  apt:
    name:
      - php-curl
      - php-sqlite3
      - sqlite3
    state: latest

- name: Create deployment directory
  file:
    path: '{{ mdata_deploy_directory }}'
    state: directory
    owner: www-data
    group: www-data

- name: Create database directory
  file:
    path: '{{ mdata_db_directory }}'
    state: directory
    owner: www-data
    group: www-data

- name: Initialize sqlite database (user db) if not exists
  command:
    cmd: 'sqlite3 {{ mdata_db_directory}}/mdata.sqlite3 "VACUUM;"'
    creates: '{{mdata_db_directory}}/mdata.sqlite3'

- name: Fix user db permissions
  file:
    path: '{{ mdata_db_directory }}'
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: Download up to date mdata sources
  git:
    repo: 'https://{{ gitlab_deploy_user }}:{{ gitlab_deploy_password }}@gitlab.mnhn.lu/section-BD/internet/mdata.git'
    dest: '{{ mdata_deploy_directory }}'
    version: configuration-file
    force: yes
  vars:
    gitlab_deploy_user: '{{ vault_gitlab_deploy_user }}'
    gitlab_deploy_password: '{{ vault_gitlab_deploy_password }}'
  notify:
    'Reload nginx'

- name: Configure mdata
  template:
    src: config.php.j2
    dest: '{{ mdata_deploy_directory }}/config.php'

- name: Install nginx site file
  template:
    src: mdata.mnhn.lu.j2
    dest: /etc/nginx/sites-available/mdata.mnhn.lu
  vars:
    root: '{{ mdata_deploy_directory }}/web'
    host: '{{ ansible_host }}'
    socket_path: '/var/run/php/php-fpm.sock'
  notify:
    'Reload nginx'

- name: Activate site
  file:
    src: /etc/nginx/sites-available/mdata.mnhn.lu
    dest: /etc/nginx/sites-enabled/mdata.mnhn.lu
    state: link
  notify:
    'Reload nginx'

- name: Crontab csv export
  cron:
    name: CSV export generation (every minute)
    cron_file: mdata_queue
    state: present
    user: php-fpm
    job: '{{ mdata_deploy_directory }}/cli/queu_downloads.php >> {{ mdata_deploy_directory }}/log/queu_downloads.log'
