---

- name: Import elasticsearch repo keys
  get_url:
    url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    dest: /etc/apt/trusted.gpg.d/elasticsearch.asc
    mode: 0644

- name: Add Elasticsearch repo
  apt_repository:
    state: present
    filename: 99-elasticsearch
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'

- name: Install latest elasticsearch
  apt:
    update_cache: yes
    name: elasticsearch
    state: latest

- name: Enable & start elasticsearch service
  service:
    name: elasticsearch
    enabled: yes
    state: started
  notify:
    - 'Restart elasticsearch'

# - name: Reset user elastic's password
#   shell:
#     cmd: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i -s <<< $'y\n{{ elasticsearch_password }}\n{{ elasticsearch_password }}\n'"
#     executable: /bin/bash
