---

- name: Import elasticsearch repo keys
  shell: 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -'

- name: Add Elasticsearch repo
  apt_repository:
    state: present
    filename: 99-elasticsearch
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'

- name: Install latest elasticsearch
  apt:
    update_cache: yes
    name: elasticsearch
    state: latest

- name: Reset user elastic's password
  shell:
    cmd: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i -s <<< $'y\n{{ elasticsearch_password }}\n{{ elasticsearch_password }}\n'"
    executable: /bin/bash

- name: Enable elasticsearch service
  service:
    name: elasticsearch
    enabled: yes
  notify:
    - 'Restart elasticsearch'
