---

- name: Install php-fpm
  apt:
    name: php-fpm
    state: latest
    
- name: Set larger maximum upload and post size
  lineinfile:
    regexp: '{{ item.name }} ='
    line: '{{ item.name }} = {{ item.value }}'
    path: /etc/php/7.4/fpm/php.ini
  notify:
    - 'Restart php-fpm'
  loop:
    - name: upload_max_filesize
      value: '{{ php_fpm_max_filesize }}'
    - name: post_max_size
      value: '{{ php_fpm_max_filesize }}'
    - name: memory_limit
      value: '{{ php_fpm_memory_limit}}'

- name: Configure php-fpm to use msmtp for sending mail, disable fix_pathinfo
  lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  notify:
    - 'Restart php-fpm'
  loop:
    - line: 'sendmail_path = "/usr/bin/msmtp -t -i"'
      regexp: 'sendmail_path ='
    - line: 'cgi.fix_pathinfo=0' # https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
      regexp: 'cgi.fix_pathinfo=$'

- name: Enable service and start
  service:
    name: php7.4-fpm
    enabled: yes
  notify:
    - 'Restart php-fpm'
