---

- name: Install TLS certs and systemd scheduled task that renews it
  tags: https
  block:
    - name: install certbot and nginx plugin
      apt:
        name: [certbot, python3-certbot-nginx]
        state: present

    - name: have certbot get a certificate and configure nginx and install systemd timer or renew
      command: 'certbot --nginx --domains {{ domain }} --email {{ email }} --agree-tos --non-interactive --redirect'
      notify: 'Restart nginx'
